Checkoutpage
JimothyGreene/EE461L-Group2-FinalProject pull request #41
Opened 2021-03-20 22:01 UTC by philipsarkis

Worked on Checkout page and some other things

2021-03-25 18:27 UTC, maxwithrow requested changes
Why was App.js deleted? The UI is not building or displaying anything when trying to spin it up

2021-03-25 22:59 UTC, sriraman2000 approved these changes

2021-03-25 22:59 UTC, sriraman2000 reviewed
Im guessing App.js not supposed to be deleted then

2021-03-31 21:10 UTC, maxwithrow approved these changes
Looks pretty good, we may want to make some small tweaks once the data from the backend starts coming in, but for where we are at atm this is good. Nice work and approved.

2021-04-01 01:06 UTC, merged