Basic CRUD for projects
JimothyGreene/EE461L-Group2-FinalProject pull request #59
Opened 2021-03-26 20:12 UTC by mxchen2001

Problem
Our API did not expose any endpoints to interact with the projects in our database. The frontend did not have access to project information

Solution
Create CRUD (Create, Read, Update, Delete) operations for projects. Projects have 3 fields: name, description, and creator id. All of these routes are protected with the JWT authentication, so only authorized users may use these endpoints.

Testing
I tested all these endpoints in Postman. I was able to Create, Read, Update, Delete projects in the project's collection in MongoDB.

Notes
We have not decided if some of the fields should stay immutable such as creator id. This does not validate inputs in any way. That will be addressed in a future PR.

Closes #27

2021-03-26 21:05 UTC, JimothyGreene requested changes
Update the Swagger docs to reflect this new API

2021-03-26 21:10 UTC, ishan0102 requested changes
Get creator ID from JWT token

2021-03-27 20:08 UTC, JimothyGreene requested changes

2021-03-27 20:08 UTC, JimothyGreene commented on swagger/EndpointDocumentation/Projects/project_w_id.yml
> +put:
Separate these per route. So there's one file for each route. So like `create.yml`, `update.yml`, etc. to keep it consistent with the users thing

2021-03-27 20:08 UTC, JimothyGreene commented on server/api/routes/projects.py
> +    return Projects.objects.to_json(), 200
We should make this so it only returns the projects associated with that specific user. So they can't just look at everyone's projects.

2021-03-27 20:10 UTC, JimothyGreene commented on swagger/EndpointDocumentation/Projects/project_w_id.yml
> +put:
I'm realizing this may not be possible with the way openAPI is setup. If it is possible, that's what I would recommend. Otherwise, not a big deal

2021-04-01 22:49 UTC, ishan0102 approved these changes
LGTM

2021-04-01 22:50 UTC, JimothyGreene approved these changes
LgTm

2021-04-01 22:51 UTC, merged